### ISSUE TITLE
v0.6 precompile error:  no method matching subtypes

### ISSUE THREAD

**Issue by lobingera** [JuliaGraphics/ColorTypes.jl#66] opened 2017-01-21 09:12 UTC
This should have meaning to someone, i tripped over it via Pkg.test("Cairo") and precompiling the requires.
```
ERROR: LoadError: LoadError: MethodError: no method matching subtypes(::Type{ColorTypes.Color})
Closest candidates are:
  subtypes(::Module, ::DataType) at reflection.jl:316
  subtypes(::DataType) at reflection.jl:333
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:532
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:532
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /home/lobi/.julia/v0.6/ColorTypes/src/types.jl, in expression starting on line 417
while loading /home/lobi/.julia/v0.6/ColorTypes/src/ColorTypes.jl, in expression starting on line 56
ERROR: LoadError: Failed to precompile ColorTypes to /home/lobi/.julia/lib/v0.6/ColorTypes.ji.
```

**Comment by timholy** [comment] 2017-01-21 10:07
Duplicate of #65.

**Closed by timholy** 2017-01-21 10:07 UTC
